<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="3" time="0.048" timestamp="2022-12-06T15:55:02.701522" hostname="TS01-05"><testcase classname="test_sample" name="test_A" file="test_sample.py" line="18" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_sample" name="test_Adding" file="test_sample.py" line="22" time="0.000"><failure message="Failed: DID NOT RAISE &lt;class 'OverflowError'&gt;">def test_Adding():
        Temp = A()
        for i in range(4):
            Temp.ADD("placeholder")
&gt;       with pytest.raises(OverflowError):
E       Failed: DID NOT RAISE &lt;class 'OverflowError'&gt;

test_sample.py:27: Failed</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_sample" name="test_answer" file="test_sample.py" line="15" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>